"""Updated User and Club models to resolve relationship conflicts

Revision ID: 293e028bda93
Revises: aeec7584a038
Create Date: 2024-08-01 23:00:35.762170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293e028bda93'
down_revision = 'aeec7584a038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
