name: Flask CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: |
        pipenv --python 3.8
        pipenv install --dev
      working-directory: ./server

    - name: Ensure flake8 and autopep8 are installed
      run: pipenv install flake8 autopep8 --dev
      working-directory: ./server

    - name: Fix linting issues on Unix (Ubuntu and macOS)
      if: runner.os != 'Windows'
      run: pipenv run autopep8 --in-place --aggressive --aggressive $(find . -name "*.py")
      working-directory: ./server

    - name: Fix linting issues on Windows
      if: runner.os == 'Windows'
      run: |
        pipenv run autopep8 --in-place --aggressive --aggressive $(powershell -Command "Get-ChildItem -Recurse -Filter *.py | ForEach-Object { $_.FullName }")
      working-directory: ./server

    - name: Lint
      run: pipenv run flake8 .
      working-directory: ./server

    - name: Run tests
      run: pipenv run pytest
      working-directory: ./server
